---
apiVersion: v1
kind: Service
metadata:
  name: www
spec:
  selector:
    app: www
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: znc
spec:
  selector:
    app: znc
  ports:
    - name: irc
      port: 7000
      targetPort: irc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app: proxy
  ports:
    - name: https
      port: 443
      targetPort: https
    - name: irc
      port: 7000
      targetPort: irc
  type: ClusterIP
