---
apiVersion: v1
kind: Service
metadata:
  name: www
spec:
  selector:
    app: www
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: www
spec:
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: www
          image: katsuya94/www:latest
          ports:
            - name: http
              containerPort: 3000
