---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: znc
spec:
  template:
    metadata:
      labels:
        app: znc
    spec:
      containers:
        - name: znc
          image: katsuya94/znc:latest
          volumeMounts:
            - name: znc
              mountPath: /home/app/.znc
          ports:
            - name: irc
              containerPort: 7000
      volumes:
        - name: znc
          configMap:
            name: znc
            items:
              - key: znc.conf
                path: configs/znc.conf
                mode: 0660
      securityContext:
        runAsNonRoot: true
        fsGroup: 1337
        supplementalGroups:
          - 1337
